apiVersion: v1
kind: Service
metadata:
  name: elastic-apm-app-demo-php-without-framework
  labels:
    service: elastic-apm-app-demo-php-without-framework
spec:
  type: NodePort
  ports:
    - port: 80
      name: webinterface
  selector:
    app: elastic-apm-app-demo-php-without-framework
